# Single page app -> Redirect to different path
[[redirects]]
from = "/*"
to = "/"
status = 200

# Redirect with a 301
from = '/home'
to = '/'
status = 301

# Custom 404
from = '/*'
to = '/404'
status = 404