# Single page app -> Redirect to different path
[[redirects]]
from = "/*"
to = "/"
status = 200

# 301 Status redirects
[[redirects]]
from = "/home"
to = "/"
status = 301

# Custom 404
[[redirects]]
from = "/*"
to = "/"
status = 404